### ISSUE TITLE
Missing Dockerfile

### ISSUE THREAD

**Issue by Tulleb** [capsule-corp-ternoa/ternoa-node#279]
Following the current `README`, I downloaded the 1.1.0 sources and ran `podman build -t tchain .`, here is the error:
`Error: stat .../ternoa-node-1.1.0/Dockerfile: no such file or directory`

I understood I had to `cd docker` first, but it is not written in the current `master` documentation.

**Comment by markopoloparadox** [comment]
Hello

Is there a reason why you want to use the old 1.1.0 version? If you want yo get the source code with Node version set to 1.1.0 you should be using the code from the v1.2.0-rc1 tag.

**Comment by markopoloparadox** [comment]
Just for reference, here is the link to the official announcement and discussion thread regarding node upgrade: https://github.com/capsule-corp-ternoa/ternoa-hub/discussions/21

**Comment by Tulleb** [comment]
I was trying to build the 1.1.0 since it is the version written on Telemetry for all updated node.
Turn out that the 1.1.0 is actually... the `v1.2.0-rc1` 🤔

Is there a reason why these 2 versions number are different?

Anyway, thank you for the link! IMO there should be a header section from the `master` branch `README` file telling people about the current official version mainnet operator should run.
I am a senior developer and I did not think at any minute that I had to go into the `ternoa-hub` discussion thread to find out about it 🙈

**Comment by markopoloparadox** [comment]
@Tulleb 
There are actually 4 versions :)
**1. Ternoa Node (Chain) package.**
This is the version of the whole Ternoa package. It uses the following scheme major-minor-patch and the latest version is 1.2.1-rc1. Those release are available here: https://github.com/capsule-corp-ternoa/ternoa-node/releases
The Major represents a big change (like going from standalone to parachain), the Minor represent the current phase (2 means we are on phase 3), the Patch represent the subphase. 

**2. Node Version**
In order to understand what "node" version mean you need to know how substrate works. Substrate clients are made out of two parts, a native part called "node" and a wasm part called "runtime". The node version doesn't change that often and it's currently set to 1.1.0 for us.

**3. Alphanet Runtime Version**
The runtime contains most of the blockchain logic that we write and every time we add new features or change existing ones we need to increase this number. The current Alphanet version is 7.

**4. Mainnet Runtime Version**
Same as the Alphanet one but for Mainnet. The current Mainnet version is 7.

All that information is exposed when we do a release. If you go to the release section you will see what is the version of the node and runtime for a specific package.
![Screenshot from 2022-09-26 23-32-48](https://user-images.githubusercontent.com/4882434/192384661-740b02e3-b9e9-49b9-bb03-32a391f056f1.png)

II agree that this could be better documented, I will see what I can do after I come back from vacations.
About not know what to do, if you are not active on Discrod then it makes sense that you weren't aware on how to properly approach this situation. Will see if we can do something about our non-discord users.

**Comment by Tulleb** [comment]
Thank you @markopoloparadox for your time during your vacations, I really appreciate 🙏 

For further communication, maybe a specific newsletter where validators could subscribe in order to mail them when needed?
Also I will put a notification alert on the Discord **Announcement** channel from now on 👍
